pipeline {
    agent any
    parameters {
        string(name: 'string_param', defaultValue: 'string_value', description: 'string param')
        booleanParam(name: 'checkbox', defaultValue: 'false', description: 'true or false param')
        choice(name: 'choice_box', choices: ['1', '2', '3'], description: 'true or false param')
    }
    environment {
        // env-vars.html
        VERSION_NAME = '2.0.9'
        // CREDENTIALS_GLOBAL = credentials('credentials_id') // ID cam be found in Jenkins UI
    }
    // tools {
        // options are jdk, maven and gradle
        // name of the tool found in jenkins global tool config
        // maven 'Maven' // maven commands can be used now
    // }

    stages {
        stage('Conditional State') {
            // stage only runs when expression is true
            when {
                expression {
                    params.string_param == 'string_value' // if statement
                }
            }
            steps {
                script {
                    // for groovy run
                    print("When expression is true")
                    print("Building version ${VERSION_NAME}")
                }
            // can use direct sh commands or echo
            }
        }

        stage('Credentials') {
            steps {
                echo "${params.string_param}"
                echo "${params.checkbox}"
                echo "${params.choice_box}"
            }
            // withCredentials([
            //     usernamePassword(credentials: 'credentials_id', usernameVariable: USER, usernamePassword: PWD)
            // ]) {
            //     // When credentials type is username with password
            //     // Plugins required = Credentials, Credentials Binding
            //     echo "Username is ${USER} and password is ${PWD}"
            // }
        }

        stage('Load Groovy file') {
            steps {
                echo "${WORKSPACE}"
                script {
                    def groovy_file = load "${WORKSPACE}/declarative-syntax/script.groovy"
                    groovy_file.printTest()
                }
            }
        }
    }

    post {
        always {
            echo "always"
            echo "Cleaning workspace after"
            cleanWs()
        }
        success {
            echo "success"
        }
        failure {
            echo "failure"
        }
    }
}
